Repository sde-sw/blazor-interview-app, pull requests merged in 2021-09, with the labels that each got.

#16 Add report feature, add random extensions
  src/Client/Dialogs/ReportDialog.razor
  src/Client/Dialogs/ReportDialog.razor.cs
  src/Client/Extensions/JSRuntimeExtensions.cs
  src/Client/Extensions/RandomExtensions.cs
  src/Client/Pages/Index.razor
  src/Client/Pages/Index.razor.cs
  src/Client/Program.cs
  src/Client/Shared/MainLayout.razor
  src/Client/wwwroot/index.html
  src/Client/wwwroot/js/saveAsFile.js
  src/Shared/Models/InterviewQuestion.cs
Labels: enhancement

#20 Center initial loading text, add spinner icon
  src/Client/wwwroot/index.html
Labels: enhancement

#18 Create LICENSE
  LICENSE
Labels: enhancement

#22 Fix search, add note content as searchable
  src/Client/Pages/Index.razor.cs
Labels: bug

#25 Add copy to clipboard button in report dialog
  src/Client/Dialogs/ReportDialog.razor
  src/Client/Dialogs/ReportDialog.razor.cs
  src/Client/Pages/Index.razor.cs
  src/Client/Program.cs
  src/Client/Services/ClipboardService.cs
  src/Client/Services/Interface/IClipboardService.cs
Labels: enhancement

#26 Add tooltips to icon buttons, add snackbar on copy button click
  src/Client/Dialogs/ReportDialog.razor.cs
  src/Client/Pages/Index.razor
  src/Client/wwwroot/css/app.css
Labels: enhancement

#27 Update README.md
  README.md
Labels: documentation

#13 Componentize header, search and toolbar
  src/Client/Components/ControlToolbar/AppControlToolbar.razor
  src/Client/Components/ControlToolbar/AppControlToolbar.razor.cs
  src/Client/Components/ExpansionList/AppExpansionList.razor
  src/Client/Components/ExpansionList/AppExpansionList.razor.cs
  src/Client/Components/ExpansionList/AppExpansionListHeader.razor
  src/Client/Components/ExpansionList/AppExpansionListHeader.razor.cs
  src/Client/Components/ExpansionList/ExpansionListItem/AppExpansionListItem.razor
  src/Client/Components/ExpansionList/ExpansionListItem/AppExpansionListItem.razor.cs
  src/Client/Components/ExpansionList/ExpansionListItem/ExpansionListItemContent/AppExpansionListItemContent.razor
  src/Client/Components/ExpansionList/ExpansionListItem/ExpansionListItemContent/AppExpansionListItemContent.razor.cs
  src/Client/Components/ExpansionList/ExpansionListItem/ExpansionListItemTitle/AppExpansionListItemTitle.razor
  src/Client/Components/ExpansionList/ExpansionListItem/ExpansionListItemTitle/AppExpansionListItemTitle.razor.cs
  src/Client/Components/Header/AppHeader.razor
  src/Client/Components/Header/AppHeader.razor.cs
  src/Client/Dialogs/NoteDialog.razor.cs
  src/Client/Dialogs/ReportDialog.razor.cs
  src/Client/Dialogs/ResetDialog.razor.cs
  src/Client/InterviewApp.Client.csproj
  src/Client/Pages/Index.razor
  src/Client/Pages/Index.razor.cs
  src/Client/Program.cs
  src/Client/Shared/MainLayout.razor
  src/Client/wwwroot/css/app.css
  src/Shared/Models/InterviewQuestion.cs
Labels: enhancement

#29 Move index codebind logic to InterviewService
  src/Client/App.razor
  src/Client/Components/ControlToolbar/AppControlToolbar.razor.cs
  src/Client/Components/ExpansionList/AppExpansionList.razor
  src/Client/Components/ExpansionList/AppExpansionList.razor.cs
  src/Client/Components/ExpansionList/AppExpansionListHeader.razor.cs
  src/Client/Components/ExpansionList/ExpansionListItem/AppExpansionListItem.razor
  src/Client/Components/ExpansionList/ExpansionListItem/AppExpansionListItem.razor.cs
  src/Client/Components/ExpansionList/ExpansionListItem/ExpansionListItemContent/AppExpansionListItemContent.razor
  src/Client/Components/ExpansionList/ExpansionListItem/ExpansionListItemContent/AppExpansionListItemContent.razor.cs
  src/Client/Components/ExpansionList/ExpansionListItem/ExpansionListItemTitle/AppExpansionListItemTitle.razor
  src/Client/Components/Header/AppHeader.razor
  src/Client/Components/Header/AppHeader.razor.cs
  src/Client/Components/Header/AppMainHeader.razor
  src/Client/Components/Header/AppMainHeader.razor.cs
  src/Client/Constants/InterviewConstants.cs
  src/Client/Constants/ThemeConstants.cs
  src/Client/Dialogs/NoteDialog.razor
  src/Client/Dialogs/ReportDialog.razor
  src/Client/Dialogs/ReportDialog.razor.cs
  src/Client/Dialogs/ResetDialog.razor
  src/Client/Enums/InterviewQuestionListType.cs
  src/Client/Extensions/RandomExtensions.cs
  src/Client/Pages/Index.razor
  src/Client/Pages/Index.razor.cs
  src/Client/Program.cs
  src/Client/Services/Interface/IInterviewService.cs
  src/Client/Services/InterviewService.cs
  src/Client/Shared/MainLayout.razor
  src/Client/Shared/MainLayout.razor.cs
  src/Client/_Imports.razor
  src/Client/wwwroot/css/app.css
  src/Server/Program.cs
  src/Shared/Models/InterviewQuestion.cs
Labels: enhancement

#35 fix responsive ui, remove download, fix dark theme
  src/Client/Components/ControlToolbar/AppControlToolbar.razor
  src/Client/Components/ControlToolbar/AppControlToolbar.razor.cs
  src/Client/Components/ExpansionList/AppExpansionList.razor
  src/Client/Components/ExpansionList/ExpansionListItem/AppExpansionListItem.razor
  src/Client/Components/ExpansionList/ExpansionListItem/ExpansionListItemContent/AppExpansionListItemContent.razor
  src/Client/Components/Header/AppMainHeader.razor
  src/Client/Constants/ThemeConstants.cs
  src/Client/Dialogs/NoteDialog.razor
  src/Client/Dialogs/ReportDialog.razor
  src/Client/Dialogs/ReportDialog.razor.cs
  src/Client/Dialogs/ResetDialog.razor
  src/Client/InterviewApp.Client.csproj
  src/Client/Pages/Index.razor
  src/Client/Shared/MainLayout.razor.css
  src/Client/wwwroot/css/app.css
  src/Server/InterviewApp.Server.csproj
  src/Shared/InterviewApp.Shared.csproj
Labels: bug

#37 add setup interview feature
  src/Client/Constants/InterviewConstants.cs
  src/Client/Dialogs/NoteDialog.razor.cs
  src/Client/Dialogs/ReportDialog.razor.cs
  src/Client/Dialogs/ResetDialog.razor.cs
  src/Client/Dialogs/SetupDialog.razor
  src/Client/Dialogs/SetupDialog.razor.cs
  src/Client/Enums/InterviewQuestionListType.cs
  src/Client/Enums/QuestionListType.cs
  src/Client/Pages/Index.razor
  src/Client/Pages/Index.razor.cs
  src/Client/Services/Interface/IInterviewService.cs
  src/Client/Services/InterviewService.cs
  src/Client/Shared/MainLayout.razor
  src/Client/Shared/MainLayout.razor.cs
  src/Client/wwwroot/css/app.css
Labels: enhancement
